version: '3'
services:
  myapp:
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: bd_user
    ports:
      - "8080:8080"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_user
    ports:
      - "3306:3306"  # Mapeo del puerto de MySQL      
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
